{
 "title": "VCSA Network & Storage",
 "description": "Shows network interfaces traffic and filesystems usage of the VCSA",
 "tags": [
  "VCSA",
  "Disk",
  "Network"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_VCSA_REST", "query": "influxdb" },
   { "name": "DS_VCSA_TELEGRAF", "query": "influxdb" },
   {
    "name": "vcenter",
    "label": "VCSA",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\""
   },
   {
    "name": "filesystem",
    "label": "File system",
    "query": "SHOW TAG VALUES FROM \"storage\" WITH KEY = \"hrStorageDescr\" WHERE \"hostname\" =~ /$vcenter$/"
   },
   {
    "name": "nic",
    "label": "NIC",
    "query": "SHOW TAG VALUES FROM \"network\" WITH KEY = \"ifDescr\" WHERE \"hostname\" =~ /$vcenter$/"
   }
  ]
 },
 "panels": [
  { "title": "Network $nic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nic" },
  {
   "title": "Input/Output Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Input bandwidth",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "query": "SELECT non_negative_derivative(mean(\"ifInOctets\"), 1m) * 8 FROM \"network\" WHERE (\"hostname\" =~ /^$vcenter$/ AND \"ifDescr\" =~ /^$nic$/) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$nic$/" }
     ]
    },
    {
     "alias": "Output bandwidth",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$nic$/" }
     ]
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "MTU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "ifMtu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$nic$/" }
     ]
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "ifSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$nic$/" }
     ]
    }
   ]
  },
  {
   "title": "Input/Output packets discarded",
   "type": "timeseries",
   "description": "The number of inbound/outbound packets which were chosen to be discarded even though no errors had been detected to prevent their being deliverable to a higher-layer protocol. One possible reason for discarding such a packet could be to free up buffer space.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Input discards",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "ifInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$nic$/" }
     ]
    },
    {
     "alias": "Output discards",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "ifOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$nic$/" }
     ]
    }
   ]
  },
  {
   "title": "Input/Output packets errors",
   "type": "timeseries",
   "description": "The number of inbound/outbound packets that contained\nerrors preventing them from being deliverable to a higher-layer protocol.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Input errors",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$nic$/" }
     ]
    },
    {
     "alias": "Output errors",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network",
     "select": [
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$nic$/" }
     ]
    }
   ]
  },
  { "title": "Storage Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "/",
   "type": "gauge",
   "description": "OS Root filesystem.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_root",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/boot",
   "type": "gauge",
   "description": "Directory where the kernel images and boot loader configurations are stored.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_boot",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "description": "Directory used when the system is out of memory to swap to disk.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_swap",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/core",
   "type": "gauge",
   "description": "Directory where core dumps from VPXD process from the vCenter Server are stored.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_core",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/log",
   "type": "gauge",
   "description": "Directory where vCenter Server and Platform Services Controller store all logs for the environment.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_log",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/db",
   "type": "gauge",
   "description": "VMware Postgres database storage location.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_db",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/dblog",
   "type": "gauge",
   "description": "VMware Postgres database logging location.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_dblog",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/seat",
   "type": "gauge",
   "description": "Stats, Events, Alarms and Tasks (SEAT) directory for VMware Postgres.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_seat",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/netdump",
   "type": "gauge",
   "description": "VMware Netdump collector repository that stores ESXi dumps.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_netdump",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/autodeploy",
   "type": "gauge",
   "description": "VMware Auto Deploy repository that stores the thinpackages used for stateless booting of ESXi hosts.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_autodeploy",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/imagebuilder",
   "type": "gauge",
   "description": "VMware Image Builder repository that stores the vSphere image profiles, software depots and VIB packages, such as driver VIBs and update VIBs.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_imagebuilder",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/updatemgr",
   "type": "gauge",
   "description": "VMware Update Manager repository where patches and updates are stored for Virtual Machine and ESXi hosts.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_updatemgr",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/archive",
   "type": "gauge",
   "description": "VMware Postgres database’s Write-Ahead Logging (WAL) location.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_archive",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/vtsdb",
   "type": "gauge",
   "description": "VMware vTSDB Service Repository that stores the stats.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_vtsdb",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/vtsdblog",
   "type": "gauge",
   "description": "VMware vTSDB Service Repository that stores the logs of the service.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_vtsdblog",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "/storage/lifecycle",
   "type": "gauge",
   "description": "Workload Control Plane service stage directory or software depot, this stores the binaries for install and update/upgrade.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fs_lifecycle",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  { "title": "Storage History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "FS $filesystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "repeat": "filesystem",
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "alias": "Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "hrStorageSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 4096" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "hrStorageDescr", "operator": "=~", "value": "/^$filesystem$/" }
     ]
    },
    {
     "alias": "Used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storage",
     "select": [
      [
       { "params": [ "hrStorageUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 4096" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" },
      { "condition": "AND", "key": "hrStorageDescr", "operator": "=~", "value": "/^$filesystem$/" }
     ]
    }
   ]
  },
  {
   "title": "Mapping device to logical volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 }
  },
  {
   "title": "Device mapper",
   "type": "table",
   "description": "The device mapper is a framework provided by the Linux kernel for mapping physical block devices onto higher-level virtual block devices.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "devmapper",
     "select": [
      [
       { "params": [ "swap1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "swap" ], "type": "alias" }
      ],
      [
       { "params": [ "core" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "core" ], "type": "alias" }
      ],
      [
       { "params": [ "log" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "log" ], "type": "alias" }
      ],
      [
       { "params": [ "db" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "db" ], "type": "alias" }
      ],
      [
       { "params": [ "dblog" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "dblog" ], "type": "alias" }
      ],
      [
       { "params": [ "seat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "seat" ], "type": "alias" }
      ],
      [
       { "params": [ "netdump" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "netdump" ], "type": "alias" }
      ],
      [
       { "params": [ "autodeploy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "autodeploy" ], "type": "alias" }
      ],
      [
       { "params": [ "imagebuilder" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "imagebuilder" ], "type": "alias" }
      ],
      [
       { "params": [ "updatemgr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "updatemgr" ], "type": "alias" }
      ],
      [
       { "params": [ "archive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "archive" ], "type": "alias" }
      ],
      [
       { "params": [ "vtsdb" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "vtsdb" ], "type": "alias" }
      ],
      [
       { "params": [ "vtsdblog" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "vtsdblog" ], "type": "alias" }
      ],
      [
       { "params": [ "lifecycle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "lifecycle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "LV Read",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "LV Read dm-0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-0",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-1",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-2",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-3",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-4",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-5",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-6",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-7",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-8",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-9",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-10",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-11",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-12",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-13",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-14",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Read dm-15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.read.rate.dm-15",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  },
  {
   "title": "LV Write",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "LV Write dm-0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-0",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-1",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-2",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-3",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-4",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-5",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-6",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-7",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-8",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-9",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-10",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-11",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-12",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-13",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-13",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-14",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-14",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    },
    {
     "alias": "LV Write dm-15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "disk.write.rate.dm-15",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$vcenter$/" }
     ]
    }
   ]
  }
 ]
}